name: docker-login

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      GH_AUTH: ${{ secrets.GH_AUTH }}
    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run: |
          docker login docker.pkg.github.com -u $DOCKER_USERNAME -p $GH_AUTH