name: dockerize

on:
  push:
    paths:
    - 'dockerize/**'

env: 
  GCLOUD_REGISTRY: ${{ secrets.GCLOUD_PROJECT_ID }}/dockerize
  GH_REGISTRY: docker.pkg.github.com/swaglive/dockerfiles/dockerize

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['0.6.1']
    env:
      GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      GH_AUTH: ${{ secrets.GH_AUTH }}
      VERSION: ${{ matrix.version }}
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: docker build dockerize/$VERSION --tag $GCLOUD_REGISTRY:$VERSION --tag $GH_REGISTRY:$VERSION
    - name: Push to Github
      run: |
          docker login docker.pkg.github.com -u $DOCKER_USERNAME -p $GH_AUTH
          docker push $GH_REGISTRY:$VERSION
    - name: Push to GCR
      uses: swaglive/actions/gcr/login@master
      with:
        args: docker push $GCLOUD_REGISTRY:$VERSION